### ISSUE TITLE
Pipe logs to std out 

### ISSUE THREAD

**Issue by metalaureate** [lloydwatkin/prosody-docker#10]
@lloydwatkin Docker processes should pipe std out to the foreground when not demonized - then I could debug in the cloud. Is there anything I can do in config to fix that?

**Comment by lloydwatkin** [comment]
You could change the log location to stdout?

**Comment by metalaureate** [comment]
Hmm. I set log paths to /dev/stdout but that didn't do anything.

**Comment by metalaureate** [comment]
Maybe I should have read the config file:

    -- "*console"; -- Log to the console, useful for debugging with daemonize=false
