### ISSUE TITLE
Can't change config

### ISSUE THREAD

**Issue by metalaureate** [lloydwatkin/prosody-docker#8]
@lloydwatkin @mwild1, hi gents I have narrowed down my difficulties to an inability to change the config file.

I could create a data container to host just the config file but that would be huge overkill - hoping you guys can see what I am doing wrong.

To override the default cfg.lua file, I try to rename it and copy in my config before calling prosody start.

```
FROM prosody/prosody:latest
RUN chmod -R +x /etc/prosody/ && chmod -R +x /var/log/prosody/ && mv /etc/prosody/prosody.cfg.lua /etc/prosody/default_prosody.cfg.lua
ADD ./configuration/prosody.cfg.lua /etc/prosody/prosody.cfg.lua
ADD ./configuration/ /etc/prosody/
ADD ./configuration/ /etc/prosody/test/
ADD ./configuration/ /etc/test/
CMD prosodyctl start
```

Adding anything to /etc/prosody has absolutely no effect. /etc/test/ gets created just fine.

```
shill$ docker exec -i -t idelog_xmpp_1 /bin/bash
root@e9af7a2818ac:/data# cd /etc/test
root@e9af7a2818ac:/etc/test# ls
prosody.cfg.lua  test.txt
root@e9af7a2818ac:/etc/test# ls -l
total 8
-rw-r--r-- 1 root root 7948 Feb  9 14:29 prosody.cfg.lua
-rw-r--r-- 1 root root    0 Feb 10 14:48 test.txt
root@e9af7a2818ac:/etc/test# cd ..
root@e9af7a2818ac:/etc# cd /etc/prosody
root@e9af7a2818ac:/etc/prosody# ls
certs  conf.d  migrator.cfg.lua  prosody.cfg.lua
root@e9af7a2818ac:/etc/prosody# ls -l
total 20
drwxr-x--- 2 root prosody 4096 Nov 24 13:10 certs
drwxr-xr-x 2 root root    4096 Oct 25 14:51 conf.d
-rw-r--r-- 1 root root     353 Oct 25 14:51 migrator.cfg.lua
-rw-r--r-- 1 root root    7682 Nov 24 13:10 prosody.cfg.lua
root@e9af7a2818ac:/etc/prosody# 

```

Stumped.

**Comment by lloydwatkin** [comment]
Right your configuration file is owned by root:root, which means prosody won't be able to read it. I believe default ownership is root:prosody, @mwild1 is that right?

**Comment by mwild1** [comment]
Yep. Any permissions are fine as long as:

* Prosody's user can read it
* Only priviliged users (e.g. root) can edit it
* Only privileged users can read it, in case it has sensitive info like DB credentials

So sensible permissions would be 640 (-rw-r-----) root:prosody

**Comment by metalaureate** [comment]
So I added 

```
 RUN chown -R root:prosody /etc/prosody/ && chown -R root:prosody /var/log/prosody/ && mv /etc/prosody/prosody.cfg.lua /etc/prosody/default_prosody.cfg.lua
```

But still get the same problem... any ideas how I can accomplish copying my config file in my Dockerfile?

**Comment by metalaureate** [comment]
If I try

```
docker run --entrypoint="cat" idelog_xmpp /etc/prosody/prosody.cfg.lua
```

It returns my config file. But this is not the config file that prosody is using.

When I try `docker exec idelog_xmpp_1 /etc/prosody/prosody.cfg.lua` to try to see what version of the config file prosody is using, I get

```
2015/02/10 21:07:07 docker-exec: failed to exec: exec: "/etc/prosody/prosody.cfg.lua": permission denied
```

**Comment by metalaureate** [comment]
Yep, well, that was stupid. I had my permissions statements being overwritten by my ADD. D'oh.
