### ISSUE TITLE
CORS errors but cross_domain_bosh = true

### ISSUE THREAD

**Issue by metalaureate** [lloydwatkin/prosody-docker#9]
@lloydwatkin @mwild1 Let me know if I should post this somewhere else: I'm experiencing CORS errors (No header set) posting to `http://groups.idelog.me:5280/http-bind `. I have `cross_domain_bosh = true` in my config. 

Can I assume that CORS is dependent on the Virtual Host defined in prosody.cfg? That is, does the destination domain of my prosody server have to match the CORS Virtual Host?

If so I need to run prosody on the same EC2 instance as my web server, or I need to set up load balancing to route that port to the prosody service.

**Comment by lloydwatkin** [comment]
Hmm I'm unsure, @mwild1 may be able to help. The usual thing is to proxy the BOSH endpoint with a webserver such as nginx, and allow that to handle the CORS headers.

I *think* you may also need a '/' (slash) on the end of your URL.

**Comment by lloydwatkin** [comment]
The best/correct place to get answers to your questions quickly (if not docker related) is the Prosody chat room at prosody@conference.prosody.im :)

**Comment by metalaureate** [comment]
Thanks for the pointers. CORS errors disappeared after I moved my prosody container on to the same host as my web server as defined in config under Virtual Hosts, which makes the domains of my BOSH request and Virtual Host definition the same. In the future, I will proxy BOSH as you suggest, to allow xmpp and web to scale independently. @mwild1 let me know if anything seems wrong here.
